# Generated by Django 3.0 on 2020-11-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default='product'),
            preserve_default=False,
        ),
    ]
