# Generated by Django 3.0 on 2020-11-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0003_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
