# Generated by Django 3.0 on 2020-11-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0004_auto_20201108_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_items',
            new_name='items',
        ),
    ]
